### ISSUE TITLE
Error on Client.set_wallet_address

### ISSUE THREAD

**Issue by Symilds** [sammchardy/python-idex#12]
Traceback (most recent call last):
  File "/home/k/PycharmProjects/idex/test.py", line 1, in <module>
    from idex.client import Client
  File "/home/k/environments/testbed_env/lib/python3.6/site-packages/idex/client.py", line 11, in <module>
    from ethereum.utils import sha3, ecsign, encode_int32
  File "/home/k/environments/testbed_env/lib/python3.6/site-packages/ethereum/__init__.py", line 11, in <module>
    from . import slogging  # noqa
  File "/home/k/environments/testbed_env/lib/python3.6/site-packages/ethereum/slogging.py", line 6, in <module>
    from ethereum.utils import bcolors, is_numeric
  File "/home/k/environments/testbed_env/lib/python3.6/site-packages/ethereum/utils.py", line 11, in <module>
    import rlp
  File "/home/k/environments/testbed_env/lib/python3.6/site-packages/rlp/__init__.py", line 1, in <module>
    from . import sedes  # noqa: F401
  File "/home/k/environments/testbed_env/lib/python3.6/site-packages/rlp/sedes/__init__.py", line 4, in <module>
    from .big_endian_int import BigEndianInt, big_endian_int  # noqa: F401
  File "/home/k/environments/testbed_env/lib/python3.6/site-packages/rlp/sedes/big_endian_int.py", line 1, in <module>
    from eth_utils import (
ImportError: cannot import name 'int_to_big_endian'

**Comment by sammchardy** [comment]
Hi @JChilds can you try updating to v0.3.0 and see if it helps
