### ISSUE TITLE
Key Error?

### ISSUE THREAD

**Issue by dipeshsoni005** [sammchardy/python-idex#13]
Traceback (most recent call last):
  File "idexV2.py", line 6, in <module>
    client = Client(address, private_key)
  File "/usr/local/lib/python3.6/dist-packages/idex/client.py", line 53, in __init__
    self.set_wallet_address(address, private_key)
  File "/usr/local/lib/python3.6/dist-packages/idex/client.py", line 170, in set_wallet_address
    self._start_nonce = nonce_res['nonce']
KeyError: 'nonce'

**Comment by sammchardy** [comment]
Hi @dipeshsoni005 I think IDEX has been down for a little bit recently. That's the most likely reason.
