### ISSUE TITLE
Error in importing Client

### ISSUE THREAD

**Issue by sunchaser68** [sammchardy/python-idex#15]
Hi, I have this error:

```
Traceback (most recent call last):
  File "***.py", line 1, in <module>
    from idex.client import Client
  File "/usr/lib/python2.7/site-packages/idex/client.py", line 10, in <module>
    from ethereum.utils import sha3, ecsign, encode_int32
  File "/usr/lib/python2.7/site-packages/ethereum-2.3.1-py2.7.egg/ethereum/__init__.py", line 11, in <module>
    from . import slogging  # noqa
  File "/usr/lib/python2.7/site-packages/ethereum-2.3.1-py2.7.egg/ethereum/slogging.py", line 6, in <module>
    from ethereum.utils import bcolors, is_numeric
  File "/usr/lib/python2.7/site-packages/ethereum-2.3.1-py2.7.egg/ethereum/utils.py", line 11, in <module>
    import rlp
  File "/usr/lib/python2.7/site-packages/rlp/__init__.py", line 1, in <module>
    from . import sedes  # noqa: F401
  File "/usr/lib/python2.7/site-packages/rlp/sedes/__init__.py", line 1, in <module>
    from . import raw  # noqa: F401
  File "/usr/lib/python2.7/site-packages/rlp/sedes/raw.py", line 9, in <module>
    from rlp.atomic import Atomic
  File "/usr/lib/python2.7/site-packages/rlp/atomic.py", line 4
    class Atomic(metaclass=abc.ABCMeta):
                          ^
SyntaxError: invalid syntax

```

My source:

from idex.client import Client
client = Client(***, ***)
currencies = client.get_currencies()

log("Currencies: " % currencies)
exit(0)

**Comment by sammchardy** [comment]
Hi @sunchaser68 can you try updating to v0.3.0 and see if that helps.
