### ISSUE TITLE
connection issue

### ISSUE THREAD

**Issue by ppoursaf** [sammchardy/python-idex#24]
I just try to connect and the file send me that. Can anyone can help me ? thanks :) 

`Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from idex.client import Client
  File "/usr/local/lib/python3.6/site-packages/idex/client.py", line 13, in <module>
    from .utils import sha3, ecsign, encode_int32
  File "/usr/local/lib/python3.6/site-packages/idex/utils.py", line 9, in <module>
    import coincurve
  File "/usr/local/lib/python3.6/site-packages/coincurve/__init__.py", line 1, in <module>
    from coincurve.context import GLOBAL_CONTEXT, Context
  File "/usr/local/lib/python3.6/site-packages/coincurve/context.py", line 4, in <module>
    from coincurve.flags import CONTEXT_ALL, CONTEXT_FLAGS
  File "/usr/local/lib/python3.6/site-packages/coincurve/flags.py", line 1, in <module>
    from ._libsecp256k1 import lib
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/coincurve/_libsecp256k1.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib
  Referenced from: /usr/local/lib/python3.6/site-packages/coincurve/_libsecp256k1.cpython-36m-darwin.so
  Reason: image not found`

**Comment by khranovsky1337** [comment]
Hmm, something wrong with ethereum sign libraries. Try to reinstall them with `pip install --upgrade python-idex` maybe
